import { RouteInfo } from './sidebar.metadata';
export const ROUTES: RouteInfo[] = [
  {
    path: '',
    title: 'MENUITEMS.MAIN.TEXT',
    moduleName: '',
    iconType: '',
    icon: '',
    class: '',
    groupTitle: true,
    badge: '',
    badgeClass: '',
    submenu: [],
  },
  {
    path: '',
    title: 'MENUITEMS.HOME.TEXT',
    moduleName: 'teacher-home',
    iconType: 'feather',
    icon: 'monitor',
    class: 'menu-toggle',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    submenu: [
      {
        path: '/teacher-home/lessons',
        title: 'MENUITEMS.HOME.LIST.TEACHER_LESSONS',
        moduleName: 'teacher-home',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        submenu: [],
      },

      //question
      {
        path: '/teacher-home/question',
        title: 'MENUITEMS.HOME.LIST.TEACHER_QUESTION',
        moduleName: 'question',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        submenu: [],
      },

      // mcq-question-answer
      {
        path: '/teacher-home/mcq-question-answer',
        title: 'MENUITEMS.HOME.LIST.TEACHER_MCQ_QUESTION_ANSWER',
        moduleName: 'mcq-question-answer',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        submenu: [],
      }
    ],
  },
  {
    path: '',
    title: 'MENUITEMS.ADMIN.TEXT',
    moduleName: 'admin',
    iconType: 'feather',
    icon: 'monitor',
    class: 'menu-toggle',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    submenu: [
      {
        path: '/admin/user',
        title: 'MENUITEMS.ADMIN.LIST.USER',
        moduleName: 'user',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        submenu: [],
      },
      {
        path: '/admin/academic-level',
        title: 'MENUITEMS.ADMIN.LIST.ACADEMIC_LEVEL',
        moduleName: 'academic-level',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        submenu: [],
      },
      {
        path: '/admin/academic-year',
        title: 'MENUITEMS.ADMIN.LIST.ACADEMIC_YEAR',
        moduleName: 'academic-year',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        submenu: [],
      },
      {
        path: '/admin/class',
        title: 'MENUITEMS.ADMIN.LIST.CLASS',
        moduleName: 'class',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        submenu: [],
      },
      {
        path: '/admin/class-name',
        title: 'MENUITEMS.ADMIN.LIST.CLASS-NAME',
        moduleName: 'class-name',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        submenu: [],
      },
      {
        path: '/admin/student',
        title: 'MENUITEMS.ADMIN.LIST.STUDENT',
        moduleName: 'student',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        submenu: [],
      },
      {
        path: '/admin/subject',
        title: 'MENUITEMS.ADMIN.LIST.SUBJECT',
        moduleName: 'subject',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        submenu: [],
      },
      {
        path: '/admin/example',
        title: 'MENUITEMS.ADMIN.LIST.EXAMPLE',
        moduleName: 'example',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        submenu: [],
      }
    ],
  }
  //section end admin 
];
